### ISSUE TITLE
不可以公用宝塔的安装的PHP吗

### ISSUE THREAD

**Issue by wuxianggujun** [zhamao-robot/zhamao-framework#132]
### 描述

我服务器是Ubuntu，已经安装了php8.1，为什么我运行命令
 检测到系统的 PHP 不存在 swoole 扩展，是否下载安装独立的内建 PHP 和 Composer？[Y/n] 
不可以和宝塔里面的PHP共用吗

**Comment by wuxianggujun** [comment]
PHP安装的是8.1，
使用的内建 PHP 版本: 8.0
这是什么意思

**Comment by sunxyw** [comment]
你好，把框架目录下的 `runtime/php` 文件删掉即可，框架会自动使用全局安装的 PHP 启动（即 `php -v` 的 PHP 版本）。

框架需要 Swoole 扩展才可使用，你可以在命令行执行 `php -m | grep "swoole"` 来确保当前 PHP 版本安装了 Swoole，有输出即为安装成功。如果没有，则你需要使用宝塔面板或 PECL 等方式安装 Swoole。
