### ISSUE TITLE
CQcommand的pattern匹配会将0匹配成空

### ISSUE THREAD

**Issue by yuelengqingchen** [zhamao-robot/zhamao-framework#136]
### 受影响版本

2.8.0

### 描述

![image](https://user-images.githubusercontent.com/14126590/177010171-53044a5e-02ca-4e7f-ab51-da7c1b8c3ef3.png)

![4 N4{T@J8XH{2DMI7PA8U5B](https://user-images.githubusercontent.com/14126590/177010115-71e0a4a4-523c-43b0-988e-591ae5872b44.jpg)

### 复现步骤

如图

**Comment by sunxyw** [comment]
已复现，疑似错误代码：https://github.com/zhamao-robot/zhamao-framework/blob/e7e77c99d084462ce365919f98683dc0d90fe5a2/src/ZM/global_functions.php#L149-L180

复现代码：`match_args('/test * * *', '/test 123456 1234067 899')`
![圖片](https://user-images.githubusercontent.com/31698606/177024081-44c4bd4a-8258-4126-a438-3d2b2f0512e2.png)
