### ISSUE TITLE
基于 LibOB Config 类重构 ZMConfig 的提案

### ISSUE THREAD

**Issue by sunxyw** [zhamao-robot/zhamao-framework#145]
### 描述

提议重构点：
- 继承  [OneBot\V12\Config\Config](https://github.com/botuniverse/php-libonebot/blob/9dca47b056a1dd9758ed1db309b1da77d6f6d35f/src/OneBot/V12/Config/Config.php) 类，并使用其 `get` `set` 等方法做配置项操作
- 将配置文件的读取改为预加载，并根据来源文件名作为 key 存作数组
- 支持更多的主流配置文件格式（toml, yaml）

提案实现后或可一并解决 [环境类型解析](https://github.com/zhamao-robot/zhamao-framework/projects/9#card-84959736) 及 [Trace 方法](https://github.com/zhamao-robot/zhamao-framework/projects/9#card-84959740)

### 例子

对用户端使用方式不影响，外部方法的行为不变

**Comment by crazywhalecc** [comment]
配置文件一直都是懒加载，这样也有好处，可以在单进程模型下加载后调整。

按理说这个 set 操作只是修改内存，不做回写吧？

**Comment by sunxyw** [comment]
> 配置文件一直都是懒加载，这样也有好处，可以在单进程模型下加载后调整。

是的，目前是懒加载。但我认为配置文件没有必要用懒加载，因为正常情况下所有的配置文件都是必定会被加载的，没有必要用懒加载，预加载的话性能会更好，不需要在使用时再去加载。

> 按理说这个 set 操作只是修改内存，不做回写吧？

不回写，只会影响内存中的配置，重启或重载后都会失去。

**Comment by crazywhalecc** [comment]
可以
