### ISSUE TITLE
启动框架后 swoole_error.log 中的错误信息

### ISSUE THREAD

**Issue by YiwanGi** [zhamao-robot/zhamao-framework#174]
### 受影响版本

2.8.4

### 描述

`php：8.0.17`  `swoole：4.8.5`
我的操作过程
```
composer require zhamao/framework  
vendor/bin/start init
vendor/bin/start server
```
框架启动后 `swoole_error.log` 文件中出现一条内容为 `NOTICE	php_swoole_server_rshutdown() (ERRNO 9003): worker process is terminated by exit()/die()` 的错误信息

### 复现步骤

```
composer require zhamao/framework  
vendor/bin/start init
vendor/bin/start server
```

**Comment by crazywhalecc** [comment]
尽快修复。
