### ISSUE TITLE
新日志格式草案

### ISSUE THREAD

**Issue by sunxyw** [zhamao-robot/zhamao-framework#191]
### 描述

预计格式：`[%date%] [%level%] %caller% | %body%`
增加了 `caller` 字段用于自动输出检测到的（可能的）模块名称，模块名称由调用者路径推断。
例，`vendor/xxxx/src/ZM/Event` -> `ZM > Event`，`vendor/xxx/src/OneBot/Driver` -> `OneBot > Driver`，`src/Module/Example` -> `Module > Example`。

其中每个字段可以安排不同的配色，以提高对比度及标注重要信息（级别、进程等）
同时具体信息可以保持终端原色，仅将等级字段染为等级颜色，

（候仪）同时考虑将等级字段和进程合并，例如：
- `[INFO]` + `[#0]` -> `[INFO#WK0]`
- `[WARN]` + `[MST]` -> `[WARN#MST]`

### 例子

`[2022-12-21 21:28:03] [WARN] [MST] OneBot > Driver | Workerman[entry.php] has been stopped`

**Comment by crazywhalecc** [comment]
有没有办法设计成开debug时再显示模块名称呢，平时稳定运行的时候应该不需要这么详细的日志？

而且好像之前搞过类似的功能？我记得开 debug 会显示调用的函数还是什么来着。
