### ISSUE TITLE
程序退出，报无日志路径问题

### ISSUE THREAD

**Issue by test-lin** [zhamao-robot/zhamao-framework#290]
### 受影响版本

3.0.0

### 描述

ctrl + c 退出程序时报的错，我看了下程序有段为空设置为 static::$logFile = __DIR__ . '/../workerman.log'; 的代码，应该是没起效。我还在炸毛文档里找了下相关日志配置，但是没找到。

![6C184Z)F9`$}D M`9J5 HX4](https://user-images.githubusercontent.com/12641322/218251535-7b4e8c31-e363-4bfd-bde0-a1b14110b25e.png)

### 复现步骤

ctrl + c 退出程序

**Comment by crazywhalecc** [comment]
这个应该是 Workerman 的 Log 日志问题。框架对 Workerman 进行了部分重写。
