### ISSUE TITLE
初始化框架时报错: Undefined constant "ZM\Command\GLOB_BRACE"

### ISSUE THREAD

**Issue by FishZe** [zhamao-robot/zhamao-framework#293]
### 受影响版本

3.0.0

### 描述

初始化框架报错: Undefined constant "ZM\Command\GLOB_BRACE"

系统: Ubuntu 20.04.5 LTS
经测试, ubuntu 22.04依旧报错

命令:
```
vendor/bin/zhamao init
```

报错:
```
* Framework started with built-in php.
提取框架基础文件
Undefined constant "ZM\Command\GLOB_BRACE"
[!] 安装框架失败！
```

可能会影响docker版本的zhamao框架

报错来源: 
https://github.com/zhamao-robot/zhamao-framework/blob/e5463fc15ad21156fe2a2a9e19b8cbf4cc11e93f/src/ZM/Command/InitCommand.php#L128

### 复现步骤

```
vendor/bin/zhamao init
```

**Comment by sunxyw** [comment]
感谢反馈，我们已知悉该问题并将尽快修复。
该问题原因为 `GLOB_BRACE` 在部分系统上存在不支持的情况，我在使用相关功能时欠缺考虑，没有考虑到兼容性问题，对此感到抱歉。将会尽快使用其他通用函数替代。
