### ISSUE TITLE
一键安装脚本完成后，再次使用 zhamao init 会出现 compser.json autoload.psr4 关联文件夹变更为数组

### ISSUE THREAD

**Issue by test-lin** [zhamao-robot/zhamao-framework#294]
### 描述

![Q2$ SF4AGA5{D$%NCZO}{0H](https://user-images.githubusercontent.com/12641322/218251823-38a7a16e-87e8-41bd-bc1f-4a6b18f16dc0.png)
![SL{TG }3X}Q3{I8$VH8V4O6](https://user-images.githubusercontent.com/12641322/218251834-8b6aa6ab-be02-4c29-ad7a-8cd219407479.png)

### 例子

我当前未查看 composer.json 相关配置规则，如果我来解决的话

- 会对 psr4 里的内容判断，如果是数组去重处理后，数组数量为1个时就改变值为字符串值

**Comment by FishZe** [comment]
同样遇到过这个问题

**Comment by sunxyw** [comment]
感谢你的反馈，此问题是因错误使用 `array_merge_recursive` 函数导致的，将会在下一版本修复。
你可以将 `vendor/zhamao/framework/src/ZM/Command/InitCommand.php` 中第 65 行的 `array_merge_recursive` 更改为 `array_merge` 来解决此问题。
