### ISSUE TITLE
有关 GitHub Action 的更新需求

### ISSUE THREAD

**Issue by crazywhalecc** [zhamao-robot/zhamao-framework#317]
### 描述

1. 在 Release 之后，调用框架的 build 命令，打包 Phar，通过 Action 发布到 Release Assets 内。
2. 在 push 了有关 class-alias 文件的更新之后，调用框架的 generate:text class-alias-md 命令，生成新的类别名文档。
3. 在 Release 之后，调用框架的 generate:text update-log-md 命令，生成更新日志到文档并 push。

**Comment by sunxyw** [comment]
closed by #318
