### ISSUE TITLE
mysql  fetchAllKeyValue 和 fetchAllAssociativeIndexed用不了，fetchone只返回true

### ISSUE THREAD

**Issue by yuelengqingchen** [zhamao-robot/zhamao-framework#56]
### 受影响版本

2.6.1

### 描述

如题

### 复现步骤

见附加图片

### 附加信息

![WUO@06 (FGC5C%KB78ZDD7B](https://user-images.githubusercontent.com/14126590/144974479-628a58c2-7752-4377-8301-c97f22486cdb.png)
![2Y$ODMFCFBU$ }1`HN)D{IV](https://user-images.githubusercontent.com/14126590/144974489-28d1fbae-1d48-4e7b-bc78-ed7f390eb105.jpg)

**Comment by crazywhalecc** [comment]
请提供表结构和数据库版本相关信息，本地将复现操作后确认

**Comment by yuelengqingchen** [comment]
> 请提供表结构和数据库版本相关信息，本地将复现操作后确认
CREATE TABLE `dynamics_test` (
  `id` int NOT NULL AUTO_INCREMENT,
  `d_time` bigint DEFAULT NULL COMMENT '动态时间',
  `rid` bigint DEFAULT NULL COMMENT '机器人id',
  `gid` bigint DEFAULT NULL COMMENT '群号',
  `status` int DEFAULT NULL COMMENT '状态，0：发送失败，1：发送成功，2：关闭了动态',
  `fail_reason` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '失败原因',
  `create_time` bigint DEFAULT NULL COMMENT '生成时间',
  `update_time` bigint DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
)
mysql版本mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
应该和表结构没关系，测试过其他表也会复现bug

**Comment by crazywhalecc** [comment]
经测试，应该是 Swoole 的 PDO 代理和 doctrine dbal 组件实现之间有差别，具体将下个 build 修复。
