### ISSUE TITLE
建议适配QQ频道官方机器人

### ISSUE THREAD

**Issue by yuelengqingchen** [zhamao-robot/zhamao-framework#59]
### 描述

注册：https://bot.q.qq.com/
注册后会定时被邀请至官方频道
测试频道创建权限申请：https://docs.qq.com/form/page/DSmF1SEVoU1lDckVS?_w_tencentdocx_form=1

**Comment by crazywhalecc** [comment]
炸毛框架目前没有打算直接实现关于其他平台的 Adapter（目前实现了 OneBot 11 和 OneBot 10 标准的聊天机器人适配器），但会实现转换器，例如内置一个将微信公众号官方接口适配器（实现原理为将其转换为 OneBot 标准）。

关于频道一块内容，OneBot 12 协议正在商讨制定当中。目前所有频道 API 在 OneBot 11 标准中的表现形式均以 go-cqhttp 为基础，官方 QQ 频道机器人的支持将会放入独立的新项目中进行。

**Comment by crazywhalecc** [comment]
最终决定并入仓库编写适配器，但是目前还没有 demo，如果可以提供一些 demo 将会减少很多工作量！谢谢

**Comment by yuelengqingchen** [comment]
https://github.com/botuild/guild-bot-protocol @crazywhalecc
