### ISSUE TITLE
控制台输出保存为日志文件

### ISSUE THREAD

**Issue by yuelengqingchen** [zhamao-robot/zhamao-framework#61]
### 描述

如题

**Comment by crazywhalecc** [comment]
使用 daemon 运行可以保存到 swoole log 中，使用 tmux/screen 的还没有集成，后续版本会加上。

**Comment by crazywhalecc** [comment]
还有关于框架的 log 组件，在下个大版本打算更新为 PSR-3 兼容的（现在还不是 PSR-3 标准），标准的等级也都不一样。

**Comment by crazywhalecc** [comment]
已增加此功能。
