### ISSUE TITLE
建议增加全局中间件支持

### ISSUE THREAD

**Issue by sunxyw** [zhamao-robot/zhamao-framework#92]
### 描述

目前仅支持在类、方法上定义中间件，但对于全局异常捕获、权限控制、请求记录等功能未有充分支持，是否考虑增加定义全局中间件的方式？如在配置文件中声明全局中间件列表等。

**Comment by crazywhalecc** [comment]
现在有全局中间件的功能的。

<img width="558" alt="image" src="https://user-images.githubusercontent.com/20330940/161428305-d290d37e-89d9-4be0-946a-38d82e8c15bb.png">
