### ISSUE TITLE
关于新型命令注解的提案

### ISSUE THREAD

**Issue by sunxyw** [zhamao-robot/zhamao-framework#93]
### 描述

目前声明命令的方式主要是结合 `CQCommand` 注解和 `ctx()->getArg` 获取参数。

新型命令注解则类似 `Command('复读', ['复读内容', 'text'])` 等，旨在提供更便捷、易于分析的命令定义结构。

在框架内部提供参数获取、校验等，减少开发者书写重复逻辑的负担，并结合 `CommandHelpGenerator` 达到自动生成命令帮助的效果。

获取到的参数可以通过顺序注入到处理方法中。

### 例子

```php
#[CQCommand('复读')]
public function foo(): string
{
    $content = ctx()->getFullArg('请输入复读内容');
    return $content;
}

#[Command('复读', ['复读内容', 'text'])]
public function bar(string $content): string
{
    return $content;
}
```

这是可能的附加功能的草草案：
```php
class RepeatRequest extends CommandRequest
{
    public function rules()
    {
        return [
            'content' => ['required', 'string'],
        ];
    }
}

#[Command('复读')]
public function bar(RepeatRequest $request): string
{
    return $request->content;
}

**Comment by crazywhalecc** [comment]
这个我在计划中有一个 @CommandArgument 的注解，只是因为配套的解析功能还没有写完，所以一直没有提新分支：

<https://gist.github.com/crazywhalecc/47b3e53f9604a797578feebd0a0803c1>

**Comment by sunxyw** [comment]
Duplicate of #111
