### ISSUE TITLE
在输入不可用情况下执行模块解包命令会导致报错

### ISSUE THREAD

**Issue by sunxyw** [zhamao-robot/zhamao-framework#95]
### 受影响版本

2.7.6

### 描述

在 Docker 等输入流不可用的情况下，`fopen(stdin)` 会返回 `false`，而框架内部未有处理，会导致在传给 `trim` 时发生报错。

### 复现步骤

在输入流不可用的情况下解包任意模块。

### 解决方案

针对输入流不可用的情况（返回 `false`）进行特别处理，如归为默认值。

### 附加信息

![圖片](https://user-images.githubusercontent.com/31698606/161434950-428643dc-1d2b-4ae1-a35b-1fb9ff734a4e.png)

OP: 依古比古咕咕咕 3053473706

**Comment by crazywhalecc** [comment]
这是个通病问题，之前在搞终端的命令输入 `reload` 那个功能的时候也遇到过这样的问题，所以框架启动有一个选项 `--disable-input`。

理论上框架 Docker 执行可以使用 `-it` 参数支持输入输出交互，但这么说也是个问题，当不存在输入设备时就会导致崩溃。

**Comment by sunxyw** [comment]
这个是因为 fgets 在输入流不可用的情况下会返回 false，而框架直接将返回值传给 trim 才报错的，所以理论上只需要对 false 进行处理就可以解决了。
